import { SchedulableUnit } from "./SchedulingTypes";

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2C — Chunk Graph Types
//
// These types model the adaptive execution state and fragmentation topology
// of the planner. They transition the scheduler from atomic indivisible tasks
// to a continuous execution flow, with dynamic chunking and dependency logic.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Defines the execution lifecycle of a chunk.
 * Vital for replanning semantics: we do not resurrect completed chunks,
 * and we anchor active chunks.
 *
 * LEGAL STATE TRANSITIONS:
 *   pending     → active        (execution begins)
 *   active      → completed     (chunk finishes successfully)
 *   active      → interrupted   (focus broken mid-execution)
 *   interrupted → deferred      (explicitly pushed to later horizon)
 *   interrupted → active        (resume after interruption)
 *   deferred    → pending       (re-queued for future scheduling)
 *
 * ILLEGAL TRANSITIONS (must never occur — future runtime enforcement target):
 *   completed   → active        (resurrection — breaks immutability guarantee)
 *   completed   → pending       (resurrection)
 *   completed   → deferred      (resurrection)
 *   active      → pending       (lifecycle regression)
 *
 * These rules MUST be enforced by ALL systems that mutate ChunkStatus.
 * Repair engines and replanning systems are NOT exempt.
 */
export type ChunkStatus =
  | "pending"     // Not yet started
  | "active"      // Currently executing
  | "completed"   // Finished successfully — TERMINAL STATE
  | "interrupted" // Partially completed but broken focus
  | "deferred";   // Explicitly pushed to a later horizon

/**
 * A sub-component of a SchedulableTask resulting from dynamic fragmentation.
 * Explicitly extends SchedulableUnit to allow direct orchestration via the same
 * algorithms used for indivisible tasks.
 */
export interface TaskChunk extends SchedulableUnit {
  unitType: "chunk";
  
  /** ID of the parent SchedulableTask */
  parentTaskId: string;
  
  /** 0-indexed position of this chunk within the task's sequence */
  chunkIndex: number;
  
  /** True if this is the final chunk required to complete the task */
  isTerminalChunk: boolean;
  
  /** Current execution lifecycle state */
  chunkStatus: ChunkStatus;

  /**
   * Stable logical identity of this chunk's originating plan slot.
   * Preserved across splits, merges, and regenerations for lineage tracking.
   *
   * TODO: Eventually separate into:
   *   lineageId  — stable across ALL mutations (ancestral identity)
   *   instanceId — unique per physical runtime generation
   * This separation is required for correct replay diffs, displacement
   * tracking, and continuity analysis once repair cycles become frequent.
   */
  originalChunkId?: string;
}

/**
 * Defines a topological dependency between two chunks of the same task.
 * The scheduler uses this to enforce temporal ordering boundaries.
 */
export interface ChunkDependency {
  parentChunkId: string;
  childChunkId: string;
  
  /** 
   * "sequential" strictly enforces child.start >= parent.end
   * Phase 2C only implements "sequential".
   */
  dependencyType: "sequential"; 
}

/**
 * The complete fragmented topology for a single task.
 * Generated by the generateTaskChunks engine.
 */
export interface ChunkedTaskPlan {
  taskId: string;
  originalDurationMinutes: number;
  
  /** All chunks generated for this task */
  chunks: TaskChunk[];
  
  /** The set of raw directed edges enforcing sequential ordering */
  dependencies: ChunkDependency[];
  
  /**
   * Forward dependencies: chunkId -> array of child chunkIds.
   * TODO: Dependency graph construction order must itself be deterministic.
   * Iteration over this Map relies on insertion order. If graph sources are 
   * nondeterministic, replay guarantees will fail. Evolve toward a canonicalized 
   * graph structure or deterministic builder.
   */
  dependencyGraph: Map<string, string[]>;
  
  /**
   * Fast lookup graph: childId -> array of parentIds.
   * Critical for determining if a chunk's prerequisites are temporally satisfied.
   */
  reverseDependencyGraph: Map<string, string[]>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Execution & Drift Analysis
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Tracks the real-world execution reality of a task against its planned state.
 * Fed back into the replanning engine to calculate directional drift.
 */
export interface TaskExecutionState {
  taskId: string;
  
  /** Total minutes the planner originally allocated */
  plannedDuration: number;
  
  /** Total minutes actually spent working on the task */
  completedDuration: number;
  
  /** Total minutes remaining to complete the task (often adjusted by user) */
  remainingDuration: number;
  
  // ── Directional Drift Signals ──
  
  /** Ratio of (completed + remaining) / planned. >1 means task was underestimated. */
  underestimationBias: number;
  
  /** Ratio of planned / (completed + remaining). >1 means task was overestimated. */
  overestimationBias: number;
  
  /** 
   * Measure of cognitive interruptions ∈ [0.0, 1.0].
   *
   * Normalization basis:
   *   0.0  = zero interruptions — perfect sustained focus
   *   0.25 = minor instability (1–2 interruptions per chunk)
   *   0.5  = moderate instability (consistent context switching)
   *   0.75 = high instability (frequent context breaking)
   *   1.0  = maximal instability (constant interruption pattern)
   *
   * Weighting basis: derived from (interruptionCount / expectedChunks)
   * normalized against task cognitive load class.
   *
   * Interpretation thresholds (used by topology optimization):
   *   > 0.6  triggers chunk size shrink
   *   < 0.25 permits deep-work chunk expansion
   */
  focusInstabilityScore: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// TODO: Phase 4 Graph Safety — Deterministic Graph Builder
//
// Replace all ad-hoc Map<string, string[]> assembly throughout the kernel with:
//
//   buildDeterministicDependencyGraph(
//     dependencies: ChunkDependency[]
//   ): Map<string, string[]>
//
// This utility MUST sort node entries canonically (e.g. lexicographic by chunkId)
// before insertion to guarantee Map iteration order is replay-safe regardless of
// the assembly source ordering. Without this, graph traversal order can silently
// diverge between replay runs assembled from different dependency orderings.
// ─────────────────────────────────────────────────────────────────────────────
