import { SchedulableUnit } from "./SchedulingTypes";

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2C — Chunk Graph Types
//
// These types model the adaptive execution state and fragmentation topology
// of the planner. They transition the scheduler from atomic indivisible tasks
// to a continuous execution flow, with dynamic chunking and dependency logic.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Defines the execution lifecycle of a chunk.
 * Vital for replanning semantics: we do not resurrect completed chunks,
 * and we anchor active chunks.
 */
export type ChunkStatus =
  | "pending"     // Not yet started
  | "active"      // Currently executing
  | "completed"   // Finished successfully
  | "interrupted" // Partially completed but broken focus
  | "deferred";   // Explicitly pushed to a later horizon

/**
 * A sub-component of a SchedulableTask resulting from dynamic fragmentation.
 * Explicitly extends SchedulableUnit to allow direct orchestration via the same
 * algorithms used for indivisible tasks.
 */
export interface TaskChunk extends SchedulableUnit {
  unitType: "chunk";
  
  /** ID of the parent SchedulableTask */
  parentTaskId: string;
  
  /** 0-indexed position of this chunk within the task's sequence */
  chunkIndex: number;
  
  /** True if this is the final chunk required to complete the task */
  isTerminalChunk: boolean;
  
  /** Current execution lifecycle state */
  chunkStatus: ChunkStatus;
}

/**
 * Defines a topological dependency between two chunks of the same task.
 * The scheduler uses this to enforce temporal ordering boundaries.
 */
export interface ChunkDependency {
  parentChunkId: string;
  childChunkId: string;
  
  /** 
   * "sequential" strictly enforces child.start >= parent.end
   * Phase 2C only implements "sequential".
   */
  dependencyType: "sequential"; 
}

/**
 * The complete fragmented topology for a single task.
 * Generated by the generateTaskChunks engine.
 */
export interface ChunkedTaskPlan {
  taskId: string;
  originalDurationMinutes: number;
  
  /** All chunks generated for this task */
  chunks: TaskChunk[];
  
  /** The set of raw directed edges enforcing sequential ordering */
  dependencies: ChunkDependency[];
  
  /**
   * Fast lookup graph: parentId -> array of childIds.
   * Speeds up orchestration graph traversal.
   */
  dependencyGraph: Map<string, string[]>;
  
  /**
   * Fast lookup graph: childId -> array of parentIds.
   * Critical for determining if a chunk's prerequisites are temporally satisfied.
   */
  reverseDependencyGraph: Map<string, string[]>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Execution & Drift Analysis
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Tracks the real-world execution reality of a task against its planned state.
 * Fed back into the replanning engine to calculate directional drift.
 */
export interface TaskExecutionState {
  taskId: string;
  
  /** Total minutes the planner originally allocated */
  plannedDuration: number;
  
  /** Total minutes actually spent working on the task */
  completedDuration: number;
  
  /** Total minutes remaining to complete the task (often adjusted by user) */
  remainingDuration: number;
  
  // ── Directional Drift Signals ──
  
  /** Ratio of (completed + remaining) / planned. >1 means task was underestimated. */
  underestimationBias: number;
  
  /** Ratio of planned / (completed + remaining). >1 means task was overestimated. */
  overestimationBias: number;
  
  /** 
   * Measure of cognitive interruptions ∈ [0,1].
   * Derived from number of times the task was paused/interrupted relative to expected chunking.
   */
  focusInstabilityScore: number;
}
